import 'package:miko_hero/core/models/story_models.dart';

/// Separator between the segments of one page scene description.
///
/// Matches the demo generator, which already writes generation context into
/// `StoryPage.sceneDescription` as em-dash separated segments. That field is
/// the story model's non-user-facing slot reserved for the image workflow, so
/// bridge identities live there instead of in a new persisted model field.
const bridgeProvenanceSeparator = ' — ';

/// Marker introducing the master-library story identity.
const bridgeStoryMarker = 'bridge-story:';

/// Marker introducing the master-library illustration identity.
const bridgeIllustrationMarker = 'bridge-illustration:';

/// Identities of one bridge-generated page, carried inside its scene text.
///
/// The later ComfyUI milestone needs to find the PC-side rows that belong to a
/// locally stored page; keeping the identities beside the scene direction they
/// describe means no stored story has to be migrated when that work lands.
class BridgeStoryProvenance {
  /// Creates the provenance of one page of a bridge-generated story.
  const BridgeStoryProvenance({
    required this.scene,
    required this.storyId,
    required this.illustrationId,
  });

  /// English scene direction exactly as the model wrote it.
  final String scene;

  /// Master-library identity of the story this page belongs to.
  final String storyId;

  /// Master-library identity of this page's pending illustration row.
  final String illustrationId;

  /// Builds the stored scene description that keeps the scene text first.
  String toSceneDescription() {
    return <String>[
      scene,
      '$bridgeStoryMarker$storyId',
      '$bridgeIllustrationMarker$illustrationId',
    ].join(bridgeProvenanceSeparator);
  }

  /// Whether [story] was generated by the PC bridge rather than the demo.
  ///
  /// True when the first page carries bridge identities. Demo stories never
  /// do, so surfaces use this to reserve the DEMO labeling for actual demo
  /// content instead of stamping it on real AI stories.
  static bool marksStory(StoryBook story) {
    final pages = story.content.pages;
    if (pages.isEmpty) {
      return false;
    }
    return fromSceneDescription(pages.first.sceneDescription) != null;
  }

  /// Recovers bridge identities, or null for a page from another generator.
  static BridgeStoryProvenance? fromSceneDescription(String sceneDescription) {
    final segments = sceneDescription.split(bridgeProvenanceSeparator);
    final storyId = _markedValue(segments, bridgeStoryMarker);
    final illustrationId = _markedValue(segments, bridgeIllustrationMarker);
    if (storyId == null || illustrationId == null) return null;
    final sceneSegments = segments.where(
      (segment) =>
          !segment.startsWith(bridgeStoryMarker) &&
          !segment.startsWith(bridgeIllustrationMarker),
    );
    return BridgeStoryProvenance(
      scene: sceneSegments.join(bridgeProvenanceSeparator),
      storyId: storyId,
      illustrationId: illustrationId,
    );
  }
}

/// Reads the value of one marked segment, ignoring an empty identity.
String? _markedValue(List<String> segments, String marker) {
  for (final segment in segments) {
    if (!segment.startsWith(marker)) continue;
    final value = segment.substring(marker.length);
    if (value.isNotEmpty) return value;
  }
  return null;
}
